### ISSUE TITLE
Does not work in Internet Explorer

### ISSUE THREAD

**Issue by just-boris** [aws/aws-sdk-js-crypto-helpers#198]
This is a follow-up for this issue: https://github.com/aws/aws-sdk-js-v3/issues/2292

When that error was fixed now I am able to unwrap the actual error. Here is the smallest code to reproduce:

```js
import { Sha256 } from "@aws-crypto/sha256-browser";

const hash = new Sha256();
hash.update("");
hash.digest().then(
  function (result) {
    console.log("ok", result);
  },
  function (error) {
    console.log("fail", error);
  }
);
```

This code works (aka produces the hashed result) in all browsers (Chrome, Firefox, Safari) but not in IE 11.

On [this page](https://catatron.com/aws-crypto-ie-demo/) you can also see this demo live and here is [the source code](https://github.com/just-boris/aws-crypto-ie-demo) you can check out locally.

**Comment by trivikr** [comment]
Fixed in https://github.com/aws/aws-sdk-js-crypto-helpers/pull/194

**Comment by just-boris** [comment]
It was not fixed there. I tested the version after that release, this is a new bug

**Comment by trivikr** [comment]
> It was not fixed there. I tested the version after that release, this is another, different bug

The fix in https://github.com/aws/aws-sdk-js-crypto-helpers/pull/194 is not release by `@aws-crypto/sha256-browser`.
Can you get the patch locally, and test if it throws error in IE 11?

**Comment by just-boris** [comment]
Yes, it still throws the error. I updated [my demo](https://catatron.com/aws-crypto-ie-demo/) so you could see it by yourself.

The fix changed the error result from a string to an object, but it does not change the fact that this error occurs only in IE and not in other browsers.

**Comment by pavloo** [comment]
Tried `@aws-crypto/sha256-browser version 2.0.1`, it works in IE11 for me.

**Comment by justplaz** [comment]
Hi,
Previous versions of this library should have fixed this issue. In any case, we are [dropping support for IE11](https://github.com/aws/aws-sdk-js-crypto-helpers/pull/629) in the next release. See https://github.com/aws/aws-sdk-js-crypto-helpers/issues/472 for more info. Thanks!
